/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bcastillo.gradle;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public String getProduct() {
        return new Product("Banana", "fuit", 10).toString();
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());
        System.out.println(new App().getProduct());
    }
}
