/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bcastillo.gradle;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
        assertEquals("Product{name='Banana', description='fuit', price=10}", classUnderTest.getProduct());
    }
}
